services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: .
      dockerfile: apps/pulse-api/Dockerfile
    environment:
      - PORT=5011
      - MONGODB_URI=mongodb://mongo:27017/clubduty-pulse
      - JWT_SECRET=change-me
    depends_on:
      - mongo
    ports:
      - "5011:5011"

  web:
    build:
      context: .
      dockerfile: apps/pulse-web/Dockerfile
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  mongo_data:
